sailfishos/lipstick

- rpm/lipstick-qt5.spec
- src/components/launcheritem.cpp
- src/components/launcheritem.h
- src/logging.cpp
- src/logging.h
- tests/ut_launchermodel/ut_launchermodel.pro
Call sailjaild's GetAppInfo to get sandboxing mode for apps. This is
needed to make lipstick prompt for sailjail when a legacy app is
sandboxed. In that case the information can not be read from the desktop
file. Without this change prompting is left to sailjail command which
also checks whether the app can be launched. This should also simplify
cover handling by allowing lipstick to manage when to show app cover
after the prompt is approved.
> Read sandboxing mode from sailjaild

- src/components/launchermodel.cpp
onFilesUpdated() when notified of a removed file would query visible
items using itemInModel() and fall back to takeHiddenItem() to query
hidden items and then delete the found item. But itemInModel in a change
in behavior was returning hidden items too so the item was deleted but
the pointer not removed from the hidden items list.
Reverting to the old behavior of only returning visible items from
itemInModel means the takeHiddenItem code path will be taken and the
item removed from hidden items list before being deleted.
> [lipstick] Fix crash when hidden desktop files are removed. Fixes JB#54889 OMP#JOLLA-249

- src/compositor/lipstickcompositor.cpp
- src/homeapplication.cpp
- src/screenlock/screenlock.cpp
- src/screenlock/screenlock.h
- src/touchscreen/touchscreen.cpp
- src/touchscreen/touchscreen_p.h
- src/volume/volumecontrol.cpp
- src/volume/volumecontrol.h
QDBusInterface performs blocking queries in its constructor to
introspect interfaces. This may inadvertently auto start services, which
may have suprising dependencies potentially blocking executing
indefinitely.
> [lipstick] Clean up hidden instances of blocking DBus. JB#54893 OMP#JOLLA-250

- src/compositor/compositor.xml
- src/compositor/lipstickcompositor.cpp
- src/compositor/lipstickcompositor.h
- src/compositor/lipstickcompositorwindow.cpp
- src/compositor/lipstickcompositorwindow.h
Application id is used to match topmost applications to their audio
streams.
> Emit application id for topmost window.

- src/components/launchermodel.cpp
- src/components/launchermodel.h
MDesktopEntry doesn't support updating of the values when file changes.
> [lipstick] Force reloading hidden launcher when file changes. JB#56017

- src/notifications/notificationmanager.cpp
- src/notifications/notificationmanager.h
- tests/stubs/notificationmanager_stub.h
- tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp
- tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
In case of sandboxed applications GetConnectionUnixProcessID returns
pid of xdg-dbus-proxy process rather than pid of actual client. This
causes notifications to be listed as originating from xdg-dbus-proxy.
Additionally the pid queries are done via synchronous ipc while handling
incoming messages which blocks lipstick mainloop and can cause problems
elsewhere.
Implement a class for handling asynchronous xdg-dbus-proxy aware
client identification, and utilize it for handling all notification
manager D-Bus method calls that require client identification.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
> [notificationmanager] Identify xdg-dbus-proxy clients

- tests/stubs/aboutsettings_stub.h
Borderline on killing the usage of AboutSettings here. Used only
for getting the "vendor name" in NotificationManager, which isn't
even exactly the same as operating system name. This will keep
breaking on every api change.
@Tomin1 @mlehtima
> [lipstick] Delete removed methods from AboutSettings stub. JB#56808

- src/notifications/notificationmanager.cpp
- tests/ut_notificationmanager/ut_notificationmanager.cpp
Commit c14ee388fe4 switched from calling MRemoteAction::trigger() to emit a signal that can be handled outside the notificationmanager. Not sure how much this test makes sense anymore, but at least it passes now again.
Also made notificationmanager to also remove the database connection. Cleans up test run by not complaining on duplicate connection for each test.
@Tomin1 @spiiroin
> Fix ut_notificationmanager. JB#57271

- src/notifications/notificationmanager.cpp
[notif] Permit apkd transient notification to use one line. JB#57361
If both the preview summary and body are present, all notifications
coming from apkd will not use the smaller single line display. This is
used by apkd-bridge when starting alien to launch an app, recently moved
from the root apkd daemon which wasn't considered an Android notification.
> notif: Permit apkd transient notification to use one line

- tests/stubs/aboutsettings_stub.h
As AboutSettings::imei() method is no longer available, related testing
stubs in lipstick fail to compile.
Sync stubbed classes by removing imei() method from them too.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
> [tests] Remove AboutSettings::imei() stub. JB#56948

- rpm/lipstick-qt5.spec
Older versions of systemsettings plugin headers still have
AboutSettings::imei() present and that causes compilation
failures in lipstick side moc generated code.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
> [lipstick] Require nemo-qml-plugin-systemsettings >= 0.8.0. JB#56948

- src/androidnotificationpriorities
Discord is one of the most popular chat apps right now, this makes the notifications work as they should be.
> Add Discord to androidnotificationpriorities

- src/components/launcheritem.cpp
- src/components/launcheritem.h
Since we need to support desktop file names that don't conform to
reverse-DNS notation, allow an alternative name for DBusActivatable with
"X-" prefix. Both of them behave the same, but this new prefixed version
can be used with desktop-file-install.
> [lipstick] Support also X-DBusActivatable. Fixes JB#57377

- plugin/lipstickplugin.cpp
- src/homeapplication.cpp
- src/volume/volumecontrol.cpp
- src/volume/volumecontrol.h
Hardware key enabled VolumeControl can be created only from C++, can be created only once, and must be exposed to the root context of the QML engine of the HomeApplication.
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
> [lipstick] Make it possible to create VolumeControl from QML. JB#59132

- src/notifications/notificationfeedbackplayer.cpp
- src/notifications/notificationfeedbackplayer.h
- tests/stubs/notificationfeedbackplayer_stub.h
- tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp
- tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.h
The notifications might include a custom feedback either directly or indirectly via a notification category. That had a chance of ending up played wrong since the default ngf event has proper setup for the sound volumes etc. Also curiously earlier the custom sound was played on all the feedback items. Now using the "default" only if needed for custom sounds or such.
Removed the minimum priority API to make this simpler. The custom priority property (note that urgency is different) has been phasing out anyhow and didn't find too good reasons to keep it here.
@jusa @abranson @llewelld
> [lipstick] Always play custom notification sounds with default feedback. JB#59247

- src/notifications/notificationfeedbackplayer.h
Can be used when the notification is acknowledged enough, not requiring to really close the notification to get rid of a long feedback.
@abranson @llewelld
> [lipstick] Allow to remove notification feedback on qml api. JB#59267

- tests/ut_volumecontrol/ut_volumecontrol.cpp
Commit 80f6d8f0 made the volumecontrol hardware handling to be explicitly enabled. Doing so as the test expects it.
@rainemak @llewelld
> [lipstick] Fix volumecontrol unit test. JB#59248

- src/homeapplication.cpp
- src/homeapplication.h
- src/shutdownscreen.cpp
- tests/ut_shutdownscreen/ut_shutdownscreen.cpp
- tests/ut_thermalnotifier/ut_thermalnotifier.cpp
Getting a shutdown notification basically means that we are going to get a TERM signal in a couple of seconds. Using that as a cue for substituting TERM handler that triggers lipstick to make a clean exit with something else makes little sense. Especially as the candidates are async-signal unsafe code from hwcomposer-plugin (that can hang and require KILL) or default handler that makes quick and dirty exit (potentially leaving behind e.g. lock files).
Keep using the already installed lipstick signal handlers.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
> [lipstick] Do not change signal handlers on shutdown. JB#60078

- src/notifications/lipsticknotification.cpp
- src/notifications/lipsticknotification.h
- src/notifications/notificationmanager.cpp
- src/notifications/notificationmanager.h
- tests/stubs/notificationmanager_stub.h
- tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp
- tests/ut_notificationmanager/ut_notificationmanager.h
- tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
Started here with PR #11 but the input map handling was broken, handling that properly didn't seem to go along nice and the usage on notification plugin side didn't feel entirely good. So instead moved to a simpler way with https://github.com/sailfishos/nemo-qml-plugin-notifications/pull/9 . Think that should be good enough to get this moving forward now.
> Notification text action support. JB#55557

- src/notifications/lipsticknotification.h
Fixes regression:
https://github.com/sailfishos/lipstick/pull/41#issuecomment-1612784777
Avoids breaking uses that aren't aware of the new argument. Fixes default actions in notifications.
> Add default argument to actionInvoked actionText. JB#55557

- src/notifications/lipsticknotification.cpp
- src/notifications/lipsticknotification.h
- src/notifications/notificationmanager.cpp
- tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp
- tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
If an application was fetching notifications via GetNotifications(), only updating some properties, and then triggering an update, it was possible that the internal x-nemo-restored hint leaked to the application side and came back on the update, skipping feedbacks and notification popup on the update. And then finally being even saved on the notification database.
So let's once and for all make this restored status an internal detail of the lipstick notification class.
> [lipstick] Don't keep restored state on updated notifications. JB#61050

- src/notifications/lipsticknotification.cpp
- src/notifications/lipsticknotification.h
- src/notifications/notificationmanager.cpp
- src/notifications/notificationmanager.h
Introducing a separate hint set for internal properties. Ensuring that they never get even by accident over D-Bus.
Used that to store whether the source of the notification is a process with privileged group and to indicate that a notification action can be trusted.
Notification database version schema not bumped as this didn't change any existing table.
> [lipstick] Support storing privileged source of notifications. JB#60924

- src/notifications/batterynotifier.cpp
Charging started or stopped because usb (dis)connected is good for user to get confirmation by turning on the display with a critical urgency notification, but charging done is more of distraction. Thus lowering the urgency of that case.
> [lipstick] Avoid turning display on when charging is done. JB#61400

- plugin/plugin.pro
- tests/common.pri
- tests/gen-tests-xml.sh
- tools/notificationtool/notificationtool.pro
Egrep is now complaining on being obsolescent so replace that with grep -E.
Removed some pointless compiler flags too.
> Fix egrep warnings. JB#61658

- doc/doxygen.cfg
- doc/notifications/doxygen.cfg
Build has quite a bunch of warnings:
[  188s] warning: Tag 'TCL_SUBST' at line 206 of file 'doxygen.cfg' has become obsolete.
[  188s]          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[  188s] warning: Tag 'SYMBOL_CACHE_SIZE' at line 339 of file 'doxygen.cfg' has become obsolete.
[  188s]          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Etc, etc.
Executed doxygen -u on the two .cfg files.
> [lipstick] Update doxygen configuration. JB#61715

- rpm/lipstick-qt5.spec
- src/src.pro
> [lipstick] Remove unnecessary Qt5Xml dependency. JB#61735

- plugin/lipstickplugin.cpp
- plugin/lipstickplugin.h
- src/compositor/lipstickcompositor.cpp
- src/devicestate/devicestate.cpp
- src/devicestate/displaystate.cpp
- src/devicestate/displaystate.h
- src/homeapplication.cpp
- src/homewindow.cpp
- src/lipstickapi.cpp
- src/lipsticksettings.cpp
- src/lipsticksettings.h
- src/touchscreen/touchscreen.cpp
- src/touchscreen/touchscreen_p.h
- src/volume/pulseaudiocontrol.cpp
Main commit:
[lipstick] Protect a bit against no primary screen present. JB#62930
Without a screen things won't likely proceed well now, but nicer to
abort with an error message rather than just segfaulting with null
reference.
One other commit for some coding style adjustments.
> Protect screen pointer

- src/compositor/alienmanager/alienmanager.cpp
- src/compositor/alienmanager/aliensurface.cpp
- src/compositor/lipstickcompositor.cpp
- src/compositor/lipstickcompositor.h
- src/compositor/lipstickcompositorwindow.cpp
- src/compositor/lipstickrecorder.cpp
- src/compositor/lipsticksurfaceinterface.cpp
- src/compositor/windowpixmapitem.cpp
- src/compositor/windowproperty.cpp
- src/homeapplication.cpp
- src/homewindow.cpp
- src/notifications/categorydefinitionstore.cpp
- src/utilities/closeeventeater.cpp
- tests/stubs/lipstickcompositor_stub.h
Main commit:
[lipstick] Allow the homescreen to control when key back events are synhtesized. JB#62979
Still being a bit rough when compositor is filtering all events instead
of what gets the event in scenegraph stack, but at least this allows
some control when there's homescreen UI on top of the app.
> Back key control

- src/compositor/lipstickcompositorwindow.cpp
The application wasn't getting wheel events until a mouse press moved the mouse focus there. Applied now a similar handling on wheel event.
Not fully sure about all the details. In practice only the setMouseFocus() happens when launching an app and doing some wheel events, and that's also enough.
> [lipstick] Activate LipstickCompositorWindow mouse focus on wheel event. JB#62969

- src/components/launchermonitor.cpp
- src/components/launchermonitor.h
Doing that results in mysterious
"QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed:
No such file or directory", without more context. Instead
print out the bad location so the problem can be investigated.
Also switched the helper method use pointer type to make it more obvious on what is getting modified.
> [lipstick] Avoid adding non-existing directories to QFileSystemWatcher. JB#63084

- plugin/lipstickplugin.cpp
- plugin/lipstickplugin.h
The API can be used to fetch content which needs translations. Hence needs to load the translations too.
> [lipstick] Ensure the qml plugin loads translations.

- doc/doc.pro
- lipstick.pro
- src/src.pro
DBus adaptor source are generated from .xml. Whether those should
be even included in docs is one thing, but now that they get visible in
docs, at least try to be consistent between builds.
> Doc->src dependency
